### PR TITLE
Convert hashicorp/field-workshops-vault to GitHub Actions

### PR DESCRIPTION
**Pull request by hc-github-team-es-release-engineering**
Pipeline migrated from [CircleCI](https://app.circleci.com/pipelines/github/hashicorp/field-workshops-vault) :tada:

## Manual steps

Perform the following steps to complete the migration:

### hashicorp/field-workshops-vault/build-and-deploy
- [ ] Ensure environment variable is updated: `INSTRUQT_TOKEN`
- [ ] Ensure environment variable is updated: `INSTRUQT_VERSION`

### hashicorp/field-workshops-vault/nightly-build
- [ ] Ensure environment variable is updated: `INSTRUQT_TOKEN`
- [ ] Ensure environment variable is updated: `INSTRUQT_VERSION`

### CODE REVIEW

**Review by thomashashi — APPROVED** [review]
LGTM

**Review by omkensey — COMMENTED** [review]
The existing CircleCI workflows also do one job per track, but I've wondered for awhile if we maybe should write the actions so that one action handles all the tracks in a loop.

**Comment by thomashashi** [comment]
> The existing CircleCI workflows also do one job per track, but I've wondered for awhile if we maybe should write the actions so that one action handles all the tracks in a loop.

The way things have been written to use GHA changes how the various actions happen compared to how CircleCI worked:

* The deploy workflows *only* deploy a track (after verifying it), and do not test it—the track should have been tested before it was merged into the default branch for deployment. These are distinct workflows because, for example, 
```on:
  [...]
  push:
    branches:
      - 'main'
    paths:
      - 'instruqt-tracks/vault-basics/**'
```
is how we deploy a given track only when it has been changed.
* The nightly test workflow *only* tests the given track, it doesn't upload it every night when it runs. This allows GHA to run the tests in parallel, which we couldn't do if we looped through all the `instruqt-tracks` directories. This also gives us the option in the future of tracking per-track test times or results and shoving that at Datadog, so we could, for example, see if a track suddenly takes an anomalous amount of time to run a test, or if a particular track fails more often than others

**Comment by thomashashi** [comment]
"CircleCI Pipeline — Failed to fetch config.yml file." is to be expected, since we're removing CircleCI here.

**Pull request merged**
